import { eventName } from '@nestfolio/event-types';

export const LedgerCtrlEventTypes = {
  BALANCE_UPDATED: eventName('BALANCE_UPDATED'),
  BALANCE_EVENT_UPDATED: eventName('BALANCE_EVENT_UPDATED'),
  PORTFOLIO_UPDATED: eventName('PORTFOLIO_UPDATED'),
  PORTFOLIO_EVENT_UPDATED: eventName('PORTFOLIO_EVENT_UPDATED'),
  LEDGER_ENTRY_RECORDED: eventName('LEDGER_ENTRY_RECORDED'),
  LEDGER_ENTRY_EVENT_UPDATED: eventName('LEDGER_ENTRY_EVENT_UPDATED'),
  LEDGER_PROCESSING_FAILED: eventName('LEDGER_PROCESSING_FAILED'),
  LEDGER_SIMULATION_FAILED: eventName('LEDGER_SIMULATION_FAILED'),
} as const;
