direction: right

title: "advisory-adpt" {
  style: { font-size: 40; bold: true; fill: transparent; stroke: transparent }
}

source: "advisory-bus\n[Source]" { class: aws-eventbridge }

to-execution: "execution-bus\n[Target]" { class: aws-eventbridge }
to-execution-dlq: "DLQ" { class: aws-dlq }
source -> to-execution

# Flows
