direction: right

title: "Execution\nADPT\n[Cross-Domain Bridge]" {
  style: { font-size: 40; bold: true; fill: transparent; stroke: transparent }
}

target: "execution-bus\n[Target]" { class: aws-eventbridge }

execution-ingress-from-advisory: "advisory-bus\n[Source]" { class: aws-eventbridge }
execution-ingress-from-advisory-dlq: "DLQ" { class: aws-dlq }
execution-ingress-from-advisory -> target

execution-ingress-from-investor: "investor-bus\n[Source]" { class: aws-eventbridge }
execution-ingress-from-investor-dlq: "DLQ" { class: aws-dlq }
execution-ingress-from-investor -> target

# Flows
