direction: right

title: "Ledger Adapter\n[Cross-Domain Bridge]" {
  style: { font-size: 40; bold: true; fill: transparent; stroke: transparent }
}

target: "ledger-bus\n[Target]" { class: aws-eventbridge }

ledger-ingress-from-execution: "execution-bus\n[Source]" { class: aws-eventbridge }
ledger-ingress-from-execution-dlq: "DLQ" { class: aws-dlq }
ledger-ingress-from-execution -> target

# Flows
