direction: right

title: "ledger-adpt" {
  style: { font-size: 40; bold: true; fill: transparent; stroke: transparent }
}

source: "ledger-bus\n[Source]" { class: aws-eventbridge }

to-investor: "investor-bus\n[Target]" { class: aws-eventbridge }
to-investor-dlq: "DLQ" { class: aws-dlq }
source -> to-investor

to-advisory: "advisory-bus\n[Target]" { class: aws-eventbridge }
to-advisory-dlq: "DLQ" { class: aws-dlq }
source -> to-advisory

# Flows
