import { eventName } from '@nestfolio/event-types';

export const ComplianceEventTypes = {
  DECISION_APPROVED: eventName('DECISION_APPROVED'),
  DECISION_BLOCKED: eventName('DECISION_BLOCKED'),
  GUARDRAIL_VIOLATION_DETECTED: eventName('GUARDRAIL_VIOLATION_DETECTED'),
  COMPLIANCE_APPROVAL_GRANTED: eventName('COMPLIANCE_APPROVAL_GRANTED'),
  AUDIT_ARTIFACT_CREATED: eventName('AUDIT_ARTIFACT_CREATED'),
  SUITABILITY_CHECK_PASSED: eventName('SUITABILITY_CHECK_PASSED'),
  SUITABILITY_CHECK_FAILED: eventName('SUITABILITY_CHECK_FAILED'),
  AUDIT_ARTIFACT_UPDATED: eventName('AUDIT_ARTIFACT_UPDATED'),
} as const;
