export const ComplianceEventTypes = {
  DECISION_APPROVED: 'DECISION_APPROVED',
  DECISION_BLOCKED: 'DECISION_BLOCKED',
  GUARDRAIL_VIOLATION_DETECTED: 'GUARDRAIL_VIOLATION_DETECTED',
  ESCALATION_TRIGGERED: 'ESCALATION_TRIGGERED',
  COMPLIANCE_APPROVAL_GRANTED: 'COMPLIANCE_APPROVAL_GRANTED',
  AUDIT_ARTIFACT_CREATED: 'AUDIT_ARTIFACT_CREATED',
  SUITABILITY_CHECK_PASSED: 'SUITABILITY_CHECK_PASSED',
  SUITABILITY_CHECK_FAILED: 'SUITABILITY_CHECK_FAILED',
} as const;

export type ComplianceEventType =
  (typeof ComplianceEventTypes)[keyof typeof ComplianceEventTypes];
