export const LedgerEventTypes = {
  // ledger-ctrl
  BALANCE_UPDATED: 'BALANCE_UPDATED',
  PORTFOLIO_UPDATED: 'PORTFOLIO_UPDATED',
  LEDGER_ENTRY_RECORDED: 'LEDGER_ENTRY_RECORDED',
  LEDGER_PROCESSING_FAILED: 'LEDGER_PROCESSING_FAILED',
  LEDGER_SIMULATION_FAILED: 'LEDGER_SIMULATION_FAILED',

  // reconciliation-ctrl
  PORTFOLIO_DRIFT_DETECTED: 'PORTFOLIO_DRIFT_DETECTED',
  RECONCILIATION_REQUIRED: 'RECONCILIATION_REQUIRED',
  RECONCILIATION_STARTED: 'RECONCILIATION_STARTED',
  RECONCILIATION_COMPLETED: 'RECONCILIATION_COMPLETED',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  RECONCILIATION_LOCK_ACQUIRED: 'RECONCILIATION_LOCK_ACQUIRED',
  RECONCILIATION_LOCK_RELEASED: 'RECONCILIATION_LOCK_RELEASED',
  PROJECTION_REBUILT: 'PROJECTION_REBUILT',
  CORPORATE_ACTION_APPLIED: 'CORPORATE_ACTION_APPLIED',
} as const;

export type LedgerEventType =
  (typeof LedgerEventTypes)[keyof typeof LedgerEventTypes];
