import * as fs from 'node:fs';
import * as path from 'node:path';
import { EventSubjects } from '../src';

const EXPECTED = [
  'ADVISORY_STATUS_UPDATED',
  'ALPACA_ACCOUNT_CHECK',
  'ALPACA_ORDER_CANCELLED',
  'ALPACA_ORDER_CANCEL_FAILED',
  'ALPACA_ORDER_FILLED',
  'ALPACA_ORDER_PARTIALLY_FILLED',
  'ALPACA_ORDER_PLACED',
  'ALPACA_ORDER_REJECTED',
  'ALPACA_ORDER_REQUESTED',
  'ALPACA_TRANSFER_COMPLETED',
  'ALPACA_TRANSFER_FAILED',
  'ALPACA_TRANSFER_INITIATED',
  'ALPACA_TRANSFER_REQUESTED',
  'ALPHA_VANTAGE_ECONOMIC_INDICATOR_UPDATED',
  'ALPHA_VANTAGE_NEWS_UPDATED',
  'BALANCE_UPDATED',
  'CONSTRUCT_PORTFOLIO',
  'DECISION_APPROVED','DECISION_BLOCKED',
  'DECISION_CYCLE_FAILED','DECISION_CYCLE_STARTED','DECISION_PACKET_CREATED','DECISION_PACKET_UPDATED',
  'DECISION_READ_MODEL_CREATED','DECISION_READ_MODEL_UPDATED',
  'DEPOSIT_INITIATED','EXECUTION_MODE_CHANGED','EXECUTION_MODE_CHANGE_UPDATED','EXPLANATION_GENERATED',
  'FETCH_ALPHA_VANTAGE_REQUESTED','FETCH_FRED_REQUESTED','FETCH_MARKETWATCH_REQUESTED',
  'FETCH_SEC_EDGAR_REQUESTED','FETCH_YAHOO_FINANCE_REQUESTED',
  'FRED_INDICATORS_UPDATED',
  'GENERATE_NARRATIVE',
  'GOAL_UPDATED',
  'INVESTOR_PROFILE_CREATED','INVESTOR_PROFILE_SNAPSHOT_CREATED','INVESTOR_PROFILE_SNAPSHOT_UPDATED',
  'INVESTOR_PROFILE_UPDATED','MANDATE_ISSUED','MANDATE_REAFFIRMED',
  'MANDATE_REVOKED','MANDATE_SNAPSHOT_CREATED','MARKET_SNAPSHOT_REFRESH_TICK','MARKET_SNAPSHOT_UPDATED',
  'MARKETWATCH_UPDATED',
  'MONTHLY_REPORT_CREATED','MONTHLY_REPORT_UPDATED',
  'NARRATIVE_COMPLETED','NARRATIVE_FAILED',
  'NOTIFICATION_CREATED','NOTIFICATION_READ','NOTIFICATION_UPDATED','ONBOARDING_COMPLETED',
  'OPERATING_MODE_CHANGED','PORTFOLIO_COMPLETED','PORTFOLIO_FAILED','PORTFOLIO_UPDATED','RECOMMENDATION_PROPOSED',
  'SEC_10K_UPDATED','SEC_8K_FILED','SEC_PROSPECTUS_UPDATED',
  'SIM_DEPOSIT_COMPLETED','SIM_DEPOSIT_INITIATED','SIM_ORDER_FILLED','SIM_ORDER_REJECTED','SIM_ORDER_REQUESTED','SIM_WITHDRAWAL_COMPLETED','SIM_WITHDRAWAL_REQUESTED',
  'USER_CONFIRMED','USER_REJECTED',
  'WITHDRAWAL_INITIATED',
  'YAHOO_FINANCE_UPDATED',
].sort();

describe('EventSubjects registry', () => {
  it('contains exactly the migrated event names', () => {
    expect(Object.keys(EventSubjects).sort()).toEqual(EXPECTED);
  });

  it('tools/typed-fixture-registered-events.json is in sync with the TypeScript registry', () => {
    // The pure-Node gate (tools/check-typed-fixtures.mjs) cannot import TypeScript, so it reads
    // this JSON as its name-source. This test ensures the JSON never silently drifts from the
    // real registry: if you add/remove an event in EventSubjects, this test will fail until
    // you also update the JSON file.
    const jsonPath = path.join(process.cwd(), 'tools/typed-fixture-registered-events.json');
    const { registeredEvents } = JSON.parse(fs.readFileSync(jsonPath, 'utf8')) as {
      registeredEvents: string[];
    };

    expect(registeredEvents.slice().sort()).toEqual(Object.keys(EventSubjects).sort());
  });
});
