import { EventSubjects } from '../src';

const EXPECTED = [
  'DEPOSIT_INITIATED','EXECUTION_MODE_CHANGED','EXECUTION_MODE_CHANGE_UPDATED','GOAL_UPDATED',
  'INVESTOR_PROFILE_CREATED','INVESTOR_PROFILE_UPDATED','MANDATE_ISSUED','MANDATE_REAFFIRMED',
  'MANDATE_REVOKED','MONTHLY_REPORT_CREATED','MONTHLY_REPORT_UPDATED','NOTIFICATION_CREATED',
  'NOTIFICATION_READ','NOTIFICATION_UPDATED','ONBOARDING_COMPLETED','OPERATING_MODE_CHANGED',
  'RECOMMENDATION_PROPOSED','WITHDRAWAL_INITIATED',
].sort();

describe('EventSubjects registry', () => {
  it('contains exactly the migrated event names', () => {
    expect(Object.keys(EventSubjects).sort()).toEqual(EXPECTED);
  });
});
