import { eventName } from '@nestfolio/event-types';

export const MarketIntelligenceEventTypes = {
  MARKET_ANALYSIS_COMPLETED: eventName('MARKET_ANALYSIS_COMPLETED'),
  MARKET_SIGNAL_DETECTED: eventName('MARKET_SIGNAL_DETECTED'),
  MARKET_INTELLIGENCE_AGENT_INVOCATION_TRACED: eventName('MARKET_INTELLIGENCE_AGENT_INVOCATION_TRACED'),
  MARKET_SNAPSHOT_UPDATED: eventName('MARKET_SNAPSHOT_UPDATED'),
  MARKET_SNAPSHOT_REFRESH_TICK: eventName('MARKET_SNAPSHOT_REFRESH_TICK'),
} as const;

export const HANDLED_EVENT_TYPES = [
  'YAHOO_FINANCE_UPDATED',
  'MARKETWATCH_UPDATED',
  'SEC_8K_FILED',
  'FRED_INDICATORS_UPDATED',
  'ALPHA_VANTAGE_NEWS_UPDATED',
  'MARKET_SNAPSHOT_REFRESH_TICK',
] as const;

export const FEED_INGESTION_EVENT_TYPES = new Set([
  eventName('YAHOO_FINANCE_UPDATED'),
  eventName('MARKETWATCH_UPDATED'),
  eventName('SEC_8K_FILED'),
  eventName('FRED_INDICATORS_UPDATED'),
  eventName('ALPHA_VANTAGE_NEWS_UPDATED'),
]);
