import { eventName } from '@nestfolio/event-types';

export const ReconciliationEventTypes = {
  PORTFOLIO_DRIFT_DETECTED: eventName('PORTFOLIO_DRIFT_DETECTED'),
  RECONCILIATION_REQUIRED: eventName('RECONCILIATION_REQUIRED'),
  RECONCILIATION_STARTED: eventName('RECONCILIATION_STARTED'),
  RECONCILIATION_COMPLETED: eventName('RECONCILIATION_COMPLETED'),
  RECONCILIATION_RESULT_UPDATED: eventName('RECONCILIATION_RESULT_UPDATED'),
  RECONCILIATION_FAILED: eventName('RECONCILIATION_FAILED'),
  DRIFT_RECORD_UPDATED: eventName('DRIFT_RECORD_UPDATED'),
  RECONCILIATION_LOCK_ACQUIRED: eventName('RECONCILIATION_LOCK_ACQUIRED'),
  RECONCILIATION_LOCK_RELEASED: eventName('RECONCILIATION_LOCK_RELEASED'),
  PROJECTION_REBUILT: eventName('PROJECTION_REBUILT'),
  CORPORATE_ACTION_APPLIED: eventName('CORPORATE_ACTION_APPLIED'),
} as const;
