export const ReconciliationEventTypes = {
  PORTFOLIO_DRIFT_DETECTED: 'PORTFOLIO_DRIFT_DETECTED',
  RECONCILIATION_REQUIRED: 'RECONCILIATION_REQUIRED',
  RECONCILIATION_STARTED: 'RECONCILIATION_STARTED',
  RECONCILIATION_COMPLETED: 'RECONCILIATION_COMPLETED',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  RECONCILIATION_LOCK_ACQUIRED: 'RECONCILIATION_LOCK_ACQUIRED',
  RECONCILIATION_LOCK_RELEASED: 'RECONCILIATION_LOCK_RELEASED',
  PROJECTION_REBUILT: 'PROJECTION_REBUILT',
  CORPORATE_ACTION_APPLIED: 'CORPORATE_ACTION_APPLIED',
} as const;
