const preset = require('../../../jest.preset');
module.exports = {
  ...preset,
  displayName: 'decision-workflow-ctrl',
  testEnvironment: 'node',
  testMatch: ['<rootDir>/test/unit/**/*.test.ts'],
  moduleNameMapper: {
    '^@nestfolio/event-types$': '<rootDir>/../../../libs/event-types/src/index.ts',
    '^@nestfolio/agent-orchestrator$': '<rootDir>/../../../libs/agent-orchestrator/src/index.ts',
    '^@nestfolio/cdk-constructs/(.*)$': '<rootDir>/../../../libs/cdk-constructs/src/$1/index.ts',
    '^@nestfolio/event-processor$': '<rootDir>/../../../libs/event-processor/src/index.ts',
    '^@nestfolio/event-processor/(.*)$': '<rootDir>/../../../libs/event-processor/src/$1',
    '^@nestfolio/investor-adpt/domain$': '<rootDir>/../../investor/investor-adpt/src/domain/index.ts',
    '^@nestfolio/investor-bff/contracts$': '<rootDir>/../../investor/investor-bff/src/domain/contracts.ts',
    '^@nestfolio/investor-profile-ctrl/events$': '<rootDir>/../../advisory/investor-profile-ctrl/src/domain/events.ts',
    '^@nestfolio/investor-profile-ctrl/contracts$': '<rootDir>/../../advisory/investor-profile-ctrl/src/domain/contracts.ts',
    '^@nestfolio/market-intelligence-ctrl/events$': '<rootDir>/../../advisory/market-intelligence-ctrl/src/domain/events.ts',
    '^@nestfolio/market-intelligence-ctrl/contracts$': '<rootDir>/../../advisory/market-intelligence-ctrl/src/domain/contracts.ts',
    '^@nestfolio/ledger-ctrl/contracts$': '<rootDir>/../../ledger/ledger-ctrl/src/domain/contracts.ts',
    '^@nestfolio/advisory-bff/events$': '<rootDir>/../../advisory/advisory-bff/src/domain/events.ts',
    '^@nestfolio/advisory-bff/service$': '<rootDir>/../../advisory/advisory-bff/src/domain/index.ts',
    '^@nestfolio/advisory-bff/contracts$': '<rootDir>/../../advisory/advisory-bff/src/domain/contracts.ts',
    '^@nestfolio/compliance-ctrl/events$': '<rootDir>/../../advisory/compliance-ctrl/src/domain/events.ts',
    '^@nestfolio/compliance-ctrl/service$': '<rootDir>/../../advisory/compliance-ctrl/src/domain/index.ts',
    '^@nestfolio/compliance-ctrl/contracts$': '<rootDir>/../../advisory/compliance-ctrl/src/domain/contracts.ts',
    '^@nestfolio/portfolio-engine-ctrl/contracts$': '<rootDir>/../../advisory/portfolio-engine-ctrl/src/domain/contracts.ts',
    '^@nestfolio/advisory-narrative-ctrl/contracts$': '<rootDir>/../../advisory/advisory-narrative-ctrl/src/domain/contracts.ts',
    '^@nestfolio/execution-adpt/domain$': '<rootDir>/../../execution/execution-adpt/src/domain/index.ts',
    '^@nestfolio/ledger-adpt/domain$': '<rootDir>/../../ledger/ledger-adpt/src/domain/index.ts',
  },
  transform: {
    '^.+\\.[tj]sx?$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.spec.json', diagnostics: false }],
  },
  transformIgnorePatterns: ['node_modules/(?!.*p-limit/|.*yocto-queue/)'],
};
