export const BrokerCtrlEventTypes = {
  // Normalized outbound (CDC)
  ORDER_FILLED: 'ORDER_FILLED',
  ORDER_PARTIALLY_FILLED: 'ORDER_PARTIALLY_FILLED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_ESCALATED: 'ORDER_ESCALATED',
  DEPOSIT_DETECTED: 'DEPOSIT_DETECTED',
  WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
  BROKER_CIRCUIT_OPEN: 'BROKER_CIRCUIT_OPEN',
} as const;

// Events this service routes (emits to ExecutionBus for adapters)
export const BrokerCtrlRoutedEventTypes = {
  SIM_ORDER_REQUESTED: 'SIM_ORDER_REQUESTED',
  SIM_DEPOSIT_INITIATED: 'SIM_DEPOSIT_INITIATED',
  SIM_WITHDRAWAL_REQUESTED: 'SIM_WITHDRAWAL_REQUESTED',
  ALPACA_ORDER_REQUESTED: 'ALPACA_ORDER_REQUESTED',
  ALPACA_ORDER_CANCEL_REQUESTED: 'ALPACA_ORDER_CANCEL_REQUESTED',
  ALPACA_TRANSFER_REQUESTED: 'ALPACA_TRANSFER_REQUESTED',
  ALPACA_ACCOUNT_CHECK: 'ALPACA_ACCOUNT_CHECK',
} as const;

// Events this service subscribes to (adapter results)
export const BrokerCtrlInboundEventTypes = {
  ORDER_SUBMITTED: 'ORDER_SUBMITTED',
  EXECUTION_MODE_CHANGED: 'EXECUTION_MODE_CHANGED',
  DEPOSIT_INITIATED: 'DEPOSIT_INITIATED',
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  // Adapter results handled by CallbackResolver
  SIM_ORDER_FILLED: 'SIM_ORDER_FILLED',
  SIM_ORDER_REJECTED: 'SIM_ORDER_REJECTED',
  SIM_DEPOSIT_COMPLETED: 'SIM_DEPOSIT_COMPLETED',
  SIM_WITHDRAWAL_COMPLETED: 'SIM_WITHDRAWAL_COMPLETED',
  ALPACA_ORDER_FILLED: 'ALPACA_ORDER_FILLED',
  ALPACA_ORDER_PARTIALLY_FILLED: 'ALPACA_ORDER_PARTIALLY_FILLED',
  ALPACA_ORDER_REJECTED: 'ALPACA_ORDER_REJECTED',
  ALPACA_ORDER_CANCELLED: 'ALPACA_ORDER_CANCELLED',
  ALPACA_ORDER_CANCEL_FAILED: 'ALPACA_ORDER_CANCEL_FAILED',
  ALPACA_TRANSFER_COMPLETED: 'ALPACA_TRANSFER_COMPLETED',
  ALPACA_TRANSFER_FAILED: 'ALPACA_TRANSFER_FAILED',
  ALPACA_ACCOUNT_SNAPSHOT: 'ALPACA_ACCOUNT_SNAPSHOT',
} as const;
