import { eventName } from '@nestfolio/event-types';

export const BrokerCtrlEventTypes = {
  // Order lifecycle (unchanged — still emitted from NormalizedEvent CDC)
  ORDER_FILLED: eventName('ORDER_FILLED'),
  ORDER_PARTIALLY_FILLED: eventName('ORDER_PARTIALLY_FILLED'),
  ORDER_REJECTED: eventName('ORDER_REJECTED'),
  ORDER_CANCELLED: eventName('ORDER_CANCELLED'),
  ORDER_ESCALATED: eventName('ORDER_ESCALATED'),
  // Funding lifecycle — emitted from FundingEvent CDC; carry full snapshot + __version
  DEPOSIT_REQUESTED: eventName('DEPOSIT_REQUESTED'),
  DEPOSIT_DETECTED: eventName('DEPOSIT_DETECTED'),
  DEPOSIT_SETTLED: eventName('DEPOSIT_SETTLED'),
  DEPOSIT_FAILED: eventName('DEPOSIT_FAILED'),
  WITHDRAWAL_REQUESTED: eventName('WITHDRAWAL_REQUESTED'),
  WITHDRAWAL_SETTLED: eventName('WITHDRAWAL_SETTLED'),
  WITHDRAWAL_FAILED: eventName('WITHDRAWAL_FAILED'),
} as const;

// Events this service routes (emits to ExecutionBus for adapters)
export const BrokerCtrlRoutedEventTypes = {
  SIM_ORDER_REQUESTED: eventName('SIM_ORDER_REQUESTED'),
  SIM_DEPOSIT_INITIATED: eventName('SIM_DEPOSIT_INITIATED'),
  SIM_WITHDRAWAL_REQUESTED: eventName('SIM_WITHDRAWAL_REQUESTED'),
  ALPACA_ORDER_REQUESTED: eventName('ALPACA_ORDER_REQUESTED'),
  ALPACA_ORDER_CANCEL_REQUESTED: eventName('ALPACA_ORDER_CANCEL_REQUESTED'),
  ALPACA_TRANSFER_REQUESTED: eventName('ALPACA_TRANSFER_REQUESTED'),
  ALPACA_ACCOUNT_CHECK: eventName('ALPACA_ACCOUNT_CHECK'),
} as const;

// Events this service subscribes to (adapter results)
export const BrokerCtrlInboundEventTypes = {
  ORDER_SUBMITTED: eventName('ORDER_SUBMITTED'),
  EXECUTION_MODE_CHANGED: eventName('EXECUTION_MODE_CHANGED'),
  DEPOSIT_INITIATED: eventName('DEPOSIT_INITIATED'),
  WITHDRAWAL_INITIATED: eventName('WITHDRAWAL_INITIATED'),
  // Adapter results handled by CallbackResolver
  SIM_ORDER_FILLED: eventName('SIM_ORDER_FILLED'),
  SIM_ORDER_REJECTED: eventName('SIM_ORDER_REJECTED'),
  SIM_DEPOSIT_COMPLETED: eventName('SIM_DEPOSIT_COMPLETED'),
  SIM_WITHDRAWAL_COMPLETED: eventName('SIM_WITHDRAWAL_COMPLETED'),
  ALPACA_ORDER_FILLED: eventName('ALPACA_ORDER_FILLED'),
  ALPACA_ORDER_PARTIALLY_FILLED: eventName('ALPACA_ORDER_PARTIALLY_FILLED'),
  ALPACA_ORDER_REJECTED: eventName('ALPACA_ORDER_REJECTED'),
  ALPACA_ORDER_CANCELLED: eventName('ALPACA_ORDER_CANCELLED'),
  ALPACA_ORDER_CANCEL_FAILED: eventName('ALPACA_ORDER_CANCEL_FAILED'),
  ALPACA_TRANSFER_COMPLETED: eventName('ALPACA_TRANSFER_COMPLETED'),
  ALPACA_TRANSFER_FAILED: eventName('ALPACA_TRANSFER_FAILED'),
} as const;
