/**
 * Cross-domain event types published by the advisory domain.
 * These are the events that other domains may consume.
 */
export const AdvisoryCrossDomainEventTypes = {
  // → Investor + Execution
  DECISION_PACKET_CREATED: 'DECISION_PACKET_CREATED',
  DECISION_APPROVED: 'DECISION_APPROVED',
  CIRCUIT_BREAKER_TRIGGERED: 'CIRCUIT_BREAKER_TRIGGERED',
  CIRCUIT_BREAKER_RESET: 'CIRCUIT_BREAKER_RESET',
  // → Investor only
  USER_CONFIRMATION_REQUESTED: 'USER_CONFIRMATION_REQUESTED',
  EXPLANATION_GENERATED: 'EXPLANATION_GENERATED',
  DECISION_BLOCKED: 'DECISION_BLOCKED',
  ESCALATION_TRIGGERED: 'ESCALATION_TRIGGERED',
  INCIDENT_DETECTED: 'INCIDENT_DETECTED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  // → Execution only
  USER_CONFIRMED: 'USER_CONFIRMED',
} as const;

/**
 * Events ingested by the advisory domain from external domain buses.
 * The advisory adapter deploys EB rules on these foreign buses to pull events into AdvisoryBus.
 */
export const AdvisoryIngestEventTypes = {
  // From Investor
  GOAL_UPDATED: 'GOAL_UPDATED',
  RISK_PROFILE_UPDATED: 'RISK_PROFILE_UPDATED',
  OPERATING_MODE_CHANGED: 'OPERATING_MODE_CHANGED',
  MANDATE_GRANTED: 'MANDATE_GRANTED',
  MANDATE_UPDATED: 'MANDATE_UPDATED',
  MANDATE_REVOKED: 'MANDATE_REVOKED',
  // From Execution
  ORDER_FILLED: 'ORDER_FILLED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  DEPOSIT_DETECTED: 'DEPOSIT_DETECTED',
  PORTFOLIO_DRIFT_DETECTED: 'PORTFOLIO_DRIFT_DETECTED',
  BROKER_SESSION_LOST: 'BROKER_SESSION_LOST',
  STREAM_DISCONNECTED: 'STREAM_DISCONNECTED',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  // From Ledger
  PORTFOLIO_UPDATED: 'PORTFOLIO_UPDATED',
  LEDGER_PORTFOLIO_DRIFT_DETECTED: 'PORTFOLIO_DRIFT_DETECTED',
  LEDGER_RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
} as const;
