import { eventName } from '@nestfolio/event-types';

export const DecisionWorkflowEventTypes = {
  DECISION_PACKET_CREATED: eventName('DECISION_PACKET_CREATED'),
  DECISION_PACKET_UPDATED: eventName('DECISION_PACKET_UPDATED'),

  ANALYZE_INVESTOR_PROFILE: eventName('ANALYZE_INVESTOR_PROFILE'),
  ANALYZE_MARKET: eventName('ANALYZE_MARKET'),
  CONSTRUCT_PORTFOLIO: eventName('CONSTRUCT_PORTFOLIO'),
  GENERATE_NARRATIVE: eventName('GENERATE_NARRATIVE'),

  RECOMMENDATION_PROPOSED: eventName('RECOMMENDATION_PROPOSED'),
  USER_CONFIRMATION_REQUESTED: eventName('USER_CONFIRMATION_REQUESTED'),

  DECISION_FEEDBACK: eventName('DECISION_FEEDBACK'),
  DECISION_WORKFLOW_FAILED: eventName('DECISION_WORKFLOW_FAILED'),

  AGENT_OUTPUT_CREATED: eventName('AGENT_OUTPUT_CREATED'),
  AGENT_OUTPUT_UPDATED: eventName('AGENT_OUTPUT_UPDATED'),
} as const;

export const TRIGGER_EVENT_TYPES = [
  eventName('INVESTOR_PROFILE_CREATED'),
  eventName('INVESTOR_PROFILE_UPDATED'),
  eventName('PORTFOLIO_DRIFT_DETECTED'),
  eventName('ORDER_FILLED'),
  eventName('ORDER_REJECTED'),
  eventName('ORDER_CANCELLED'),
  eventName('DEPOSIT_DETECTED'),
] as const;

export const AGENT_COMPLETION_EVENT_TYPES = [
  eventName('INVESTOR_PROFILE_COMPLETED'),
  eventName('MARKET_ANALYSIS_COMPLETED'),
  eventName('PORTFOLIO_COMPLETED'),
  eventName('NARRATIVE_COMPLETED'),
] as const;

export const COMPLIANCE_EVENT_TYPES = [
  eventName('DECISION_APPROVED'),
  eventName('DECISION_BLOCKED'),
] as const;

export const USER_RESPONSE_EVENT_TYPES = [
  eventName('USER_CONFIRMED'),
  eventName('USER_REJECTED'),
] as const;

export const ALL_INBOUND_EVENT_TYPES = [
  ...AGENT_COMPLETION_EVENT_TYPES,
  ...COMPLIANCE_EVENT_TYPES,
  ...USER_RESPONSE_EVENT_TYPES,
] as const;
