export const AdvisoryCtrlEventTypes = {
  AGENT_INVOCATION_STARTED: 'AGENT_INVOCATION_STARTED',
  AGENT_INVOCATION_COMPLETED: 'AGENT_INVOCATION_COMPLETED',
  AGENT_EXECUTION_FAILED: 'AGENT_EXECUTION_FAILED',
  GOAL_INTERPRETATION_PRODUCED: 'GOAL_INTERPRETATION_PRODUCED',
  RISK_EVALUATION_PRODUCED: 'RISK_EVALUATION_PRODUCED',
  MARKET_SIGNAL_DETECTED: 'MARKET_SIGNAL_DETECTED',
  PORTFOLIO_CONSTRUCTION_PROPOSED: 'PORTFOLIO_CONSTRUCTION_PROPOSED',
  REBALANCE_PLAN_PRODUCED: 'REBALANCE_PLAN_PRODUCED',
  RECOMMENDATION_PROPOSED: 'RECOMMENDATION_PROPOSED',
  EXPLANATION_GENERATED: 'EXPLANATION_GENERATED',
  DECISION_PACKET_CREATED: 'DECISION_PACKET_CREATED',
  DECISION_PACKET_ENRICHED: 'DECISION_PACKET_ENRICHED',
  USER_CONFIRMATION_REQUESTED: 'USER_CONFIRMATION_REQUESTED',
  INCIDENT_DETECTED: 'INCIDENT_DETECTED',
  INCIDENT_CONTAINED: 'INCIDENT_CONTAINED',
  INCIDENT_ESCALATED: 'INCIDENT_ESCALATED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  CIRCUIT_BREAKER_TRIGGERED: 'CIRCUIT_BREAKER_TRIGGERED',
  CIRCUIT_BREAKER_RESET: 'CIRCUIT_BREAKER_RESET',
  HEALTH_CHECK_COMPLETED: 'HEALTH_CHECK_COMPLETED',
  MODEL_REGISTERED: 'MODEL_REGISTERED',
  SHADOW_RUN_STARTED: 'SHADOW_RUN_STARTED',
  SHADOW_RUN_COMPLETED: 'SHADOW_RUN_COMPLETED',
  MODEL_PROMOTION_REQUESTED: 'MODEL_PROMOTION_REQUESTED',
  MODEL_PROMOTION_APPROVED: 'MODEL_PROMOTION_APPROVED',
  MODEL_PROMOTED: 'MODEL_PROMOTED',
  MODEL_ROLLBACK_TRIGGERED: 'MODEL_ROLLBACK_TRIGGERED',
  TENANT_BUDGET_APPROACHING: 'TENANT_BUDGET_APPROACHING',
  TENANT_BUDGET_EXCEEDED: 'TENANT_BUDGET_EXCEEDED',
  REASONING_TIER_CHANGED: 'REASONING_TIER_CHANGED',
  OPERATOR_ACTION_PERFORMED: 'OPERATOR_ACTION_PERFORMED',
  EVENT_DELIVERY_FAILED: 'EVENT_DELIVERY_FAILED',
  EVENT_REPLAYED: 'EVENT_REPLAYED',
} as const;

export type AdvisoryCtrlEventType =
  (typeof AdvisoryCtrlEventTypes)[keyof typeof AdvisoryCtrlEventTypes];

export const AdvisoryBffEventTypes = {
  USER_CONFIRMED: 'USER_CONFIRMED',
  USER_REJECTED: 'USER_REJECTED',
  USER_VIEWED_EXPLANATION: 'USER_VIEWED_EXPLANATION',
} as const;

export type AdvisoryBffEventType =
  (typeof AdvisoryBffEventTypes)[keyof typeof AdvisoryBffEventTypes];

export const ComplianceEventTypes = {
  DECISION_APPROVED: 'DECISION_APPROVED',
  DECISION_BLOCKED: 'DECISION_BLOCKED',
  GUARDRAIL_VIOLATION_DETECTED: 'GUARDRAIL_VIOLATION_DETECTED',
  ESCALATION_TRIGGERED: 'ESCALATION_TRIGGERED',
  COMPLIANCE_APPROVAL_GRANTED: 'COMPLIANCE_APPROVAL_GRANTED',
  AUDIT_ARTIFACT_CREATED: 'AUDIT_ARTIFACT_CREATED',
  SUITABILITY_CHECK_PASSED: 'SUITABILITY_CHECK_PASSED',
  SUITABILITY_CHECK_FAILED: 'SUITABILITY_CHECK_FAILED',
} as const;

export type ComplianceEventType =
  (typeof ComplianceEventTypes)[keyof typeof ComplianceEventTypes];
