import { eventName } from '@nestfolio/event-types';

export const ExecutionAdptEventTypes = {
  ORDER_ACCEPTED: eventName('ORDER_ACCEPTED'),
  ORDER_PARTIALLY_FILLED: eventName('ORDER_PARTIALLY_FILLED'),
  ORDER_FILLED: eventName('ORDER_FILLED'),
  ORDER_REJECTED: eventName('ORDER_REJECTED'),
  ORDER_CANCELLED: eventName('ORDER_CANCELLED'),
  PORTFOLIO_SNAPSHOT_IMPORTED: eventName('PORTFOLIO_SNAPSHOT_IMPORTED'),
  BROKER_SESSION_ESTABLISHED: eventName('BROKER_SESSION_ESTABLISHED'),
  BROKER_SESSION_LOST: eventName('BROKER_SESSION_LOST'),
  STREAM_CONNECTED: eventName('STREAM_CONNECTED'),
  STREAM_DISCONNECTED: eventName('STREAM_DISCONNECTED'),
  BROKER_AUTHORIZATION_REVOKED: eventName('BROKER_AUTHORIZATION_REVOKED'),
  DEPOSIT_DETECTED: eventName('DEPOSIT_DETECTED'),
  WITHDRAWAL_SUBMITTED: eventName('WITHDRAWAL_SUBMITTED'),
  WITHDRAWAL_COMPLETED: eventName('WITHDRAWAL_COMPLETED'),
  WITHDRAWAL_REJECTED: eventName('WITHDRAWAL_REJECTED'),
} as const;

export const BrokerSimEventTypes = {
  // Inbound (from broker-ctrl)
  SIM_ORDER_REQUESTED: eventName('SIM_ORDER_REQUESTED'),
  SIM_DEPOSIT_INITIATED: eventName('SIM_DEPOSIT_INITIATED'),
  SIM_WITHDRAWAL_REQUESTED: eventName('SIM_WITHDRAWAL_REQUESTED'),

  // Outbound (CDC)
  SIM_ORDER_FILLED: eventName('SIM_ORDER_FILLED'),
  SIM_ORDER_REJECTED: eventName('SIM_ORDER_REJECTED'),
  SIM_DEPOSIT_COMPLETED: eventName('SIM_DEPOSIT_COMPLETED'),
  SIM_WITHDRAWAL_COMPLETED: eventName('SIM_WITHDRAWAL_COMPLETED'),
} as const;
