export const ExecutionAdptEventTypes = {
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_PARTIALLY_FILLED: 'ORDER_PARTIALLY_FILLED',
  ORDER_FILLED: 'ORDER_FILLED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PORTFOLIO_SNAPSHOT_IMPORTED: 'PORTFOLIO_SNAPSHOT_IMPORTED',
  BROKER_SESSION_ESTABLISHED: 'BROKER_SESSION_ESTABLISHED',
  BROKER_SESSION_LOST: 'BROKER_SESSION_LOST',
  STREAM_CONNECTED: 'STREAM_CONNECTED',
  STREAM_DISCONNECTED: 'STREAM_DISCONNECTED',
  BROKER_AUTHORIZATION_REVOKED: 'BROKER_AUTHORIZATION_REVOKED',
  DEPOSIT_DETECTED: 'DEPOSIT_DETECTED',
  WITHDRAWAL_SUBMITTED: 'WITHDRAWAL_SUBMITTED',
  WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
} as const;

export const BrokerSimEventTypes = {
  // Inbound (from broker-ctrl)
  SIM_ORDER_REQUESTED: 'SIM_ORDER_REQUESTED',
  SIM_DEPOSIT_INITIATED: 'SIM_DEPOSIT_INITIATED',
  SIM_WITHDRAWAL_REQUESTED: 'SIM_WITHDRAWAL_REQUESTED',

  // Outbound (CDC)
  SIM_ORDER_FILLED: 'SIM_ORDER_FILLED',
  SIM_ORDER_REJECTED: 'SIM_ORDER_REJECTED',
  SIM_DEPOSIT_COMPLETED: 'SIM_DEPOSIT_COMPLETED',
  SIM_WITHDRAWAL_COMPLETED: 'SIM_WITHDRAWAL_COMPLETED',
} as const;
