import { eventName } from '@nestfolio/event-types';

export const AlpacaAdptEventTypes = {
  // Inbound (from broker-ctrl)
  ALPACA_ORDER_REQUESTED: eventName('ALPACA_ORDER_REQUESTED'),
  ALPACA_ORDER_CANCEL_REQUESTED: eventName('ALPACA_ORDER_CANCEL_REQUESTED'),
  ALPACA_TRANSFER_REQUESTED: eventName('ALPACA_TRANSFER_REQUESTED'),
  ALPACA_ACCOUNT_CHECK: eventName('ALPACA_ACCOUNT_CHECK'),

  // Circuit breaker (CDC)
  BROKER_CIRCUIT_OPEN: eventName('BROKER_CIRCUIT_OPEN'),
  BROKER_CIRCUIT_CLOSED: eventName('BROKER_CIRCUIT_CLOSED'),
  BROKER_HEAL_ESCALATED: eventName('BROKER_HEAL_ESCALATED'),

  // Outbound (CDC)
  ALPACA_ORDER_PLACED: eventName('ALPACA_ORDER_PLACED'),
  ALPACA_ORDER_FILLED: eventName('ALPACA_ORDER_FILLED'),
  ALPACA_ORDER_PARTIALLY_FILLED: eventName('ALPACA_ORDER_PARTIALLY_FILLED'),
  ALPACA_ORDER_REJECTED: eventName('ALPACA_ORDER_REJECTED'),
  ALPACA_ORDER_CANCELLED: eventName('ALPACA_ORDER_CANCELLED'),
  ALPACA_ORDER_CANCEL_FAILED: eventName('ALPACA_ORDER_CANCEL_FAILED'),
  ALPACA_TRANSFER_INITIATED: eventName('ALPACA_TRANSFER_INITIATED'),
  ALPACA_TRANSFER_COMPLETED: eventName('ALPACA_TRANSFER_COMPLETED'),
  ALPACA_TRANSFER_FAILED: eventName('ALPACA_TRANSFER_FAILED'),
  ALPACA_ACCOUNT_SNAPSHOT: eventName('ALPACA_ACCOUNT_SNAPSHOT'),
} as const;
