export const AlpacaAdptEventTypes = {
  // Inbound (from broker-ctrl)
  ALPACA_ORDER_REQUESTED: 'ALPACA_ORDER_REQUESTED',
  ALPACA_ORDER_CANCEL_REQUESTED: 'ALPACA_ORDER_CANCEL_REQUESTED',
  ALPACA_TRANSFER_REQUESTED: 'ALPACA_TRANSFER_REQUESTED',
  ALPACA_ACCOUNT_CHECK: 'ALPACA_ACCOUNT_CHECK',

  // Outbound (CDC)
  ALPACA_ORDER_PLACED: 'ALPACA_ORDER_PLACED',
  ALPACA_ORDER_FILLED: 'ALPACA_ORDER_FILLED',
  ALPACA_ORDER_PARTIALLY_FILLED: 'ALPACA_ORDER_PARTIALLY_FILLED',
  ALPACA_ORDER_REJECTED: 'ALPACA_ORDER_REJECTED',
  ALPACA_ORDER_CANCELLED: 'ALPACA_ORDER_CANCELLED',
  ALPACA_ORDER_CANCEL_FAILED: 'ALPACA_ORDER_CANCEL_FAILED',
  ALPACA_TRANSFER_INITIATED: 'ALPACA_TRANSFER_INITIATED',
  ALPACA_TRANSFER_COMPLETED: 'ALPACA_TRANSFER_COMPLETED',
  ALPACA_TRANSFER_FAILED: 'ALPACA_TRANSFER_FAILED',
  ALPACA_ACCOUNT_SNAPSHOT: 'ALPACA_ACCOUNT_SNAPSHOT',
} as const;
