export const ExecutionEventTypes = {
  // execution-ctrl
  ORDER_SUBMITTED: 'ORDER_SUBMITTED',
  ORDER_STAGED: 'ORDER_STAGED',
  EXECUTION_PAUSED: 'EXECUTION_PAUSED',
  EXECUTION_RESUMED: 'EXECUTION_RESUMED',

  // execution-adpt
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_PARTIALLY_FILLED: 'ORDER_PARTIALLY_FILLED',
  ORDER_FILLED: 'ORDER_FILLED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PORTFOLIO_SNAPSHOT_IMPORTED: 'PORTFOLIO_SNAPSHOT_IMPORTED',
  BROKER_SESSION_ESTABLISHED: 'BROKER_SESSION_ESTABLISHED',
  BROKER_SESSION_LOST: 'BROKER_SESSION_LOST',
  STREAM_CONNECTED: 'STREAM_CONNECTED',
  STREAM_DISCONNECTED: 'STREAM_DISCONNECTED',
  BROKER_AUTHORIZATION_REVOKED: 'BROKER_AUTHORIZATION_REVOKED',
  DEPOSIT_DETECTED: 'DEPOSIT_DETECTED',
  WITHDRAWAL_SUBMITTED: 'WITHDRAWAL_SUBMITTED',
  WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',

  // portfolio-bff
  PORTFOLIO_CREATED: 'PORTFOLIO_CREATED',
  PORTFOLIO_UPDATED: 'PORTFOLIO_UPDATED',
  POSITION_UPDATED: 'POSITION_UPDATED',
  CASH_BALANCE_UPDATED: 'CASH_BALANCE_UPDATED',

  // portfolio-ctrl
  PORTFOLIO_DRIFT_DETECTED: 'PORTFOLIO_DRIFT_DETECTED',
  RECONCILIATION_REQUIRED: 'RECONCILIATION_REQUIRED',
  RECONCILIATION_STARTED: 'RECONCILIATION_STARTED',
  RECONCILIATION_COMPLETED: 'RECONCILIATION_COMPLETED',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  RECONCILIATION_LOCK_ACQUIRED: 'RECONCILIATION_LOCK_ACQUIRED',
  RECONCILIATION_LOCK_RELEASED: 'RECONCILIATION_LOCK_RELEASED',
  PROJECTION_REBUILT: 'PROJECTION_REBUILT',
  CORPORATE_ACTION_APPLIED: 'CORPORATE_ACTION_APPLIED',
} as const;

export type ExecutionEventType =
  (typeof ExecutionEventTypes)[keyof typeof ExecutionEventTypes];
