/**
 * Cross-domain event types published by the investor domain.
 * These are the events that other domains may consume.
 */
export const InvestorCrossDomainEventTypes = {
  // → Advisory
  GOAL_UPDATED: 'GOAL_UPDATED',
  RISK_PROFILE_UPDATED: 'RISK_PROFILE_UPDATED',
  OPERATING_MODE_CHANGED: 'OPERATING_MODE_CHANGED',
  MANDATE_CREATED: 'MANDATE_CREATED',
  MANDATE_UPDATED: 'MANDATE_UPDATED',
  MANDATE_REVOKED: 'MANDATE_REVOKED',
  // → Execution
  DEPOSIT_INITIATED: 'DEPOSIT_INITIATED',
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  ACCOUNT_CLOSURE_REQUESTED: 'ACCOUNT_CLOSURE_REQUESTED',
  EXECUTION_MODE_CHANGED: 'EXECUTION_MODE_CHANGED',
} as const;

/**
 * Events ingested by the investor domain from external domain buses.
 * The investor adapter deploys EB rules on these foreign buses to pull events into InvestorBus.
 */
export const InvestorIngestEventTypes = {
  // From Advisory
  DECISION_PACKET_CREATED: 'DECISION_PACKET_CREATED',
  USER_CONFIRMATION_REQUESTED: 'USER_CONFIRMATION_REQUESTED',
  EXPLANATION_GENERATED: 'EXPLANATION_GENERATED',
  DECISION_APPROVED: 'DECISION_APPROVED',
  DECISION_BLOCKED: 'DECISION_BLOCKED',
  ESCALATION_TRIGGERED: 'ESCALATION_TRIGGERED',
  CIRCUIT_BREAKER_TRIGGERED: 'CIRCUIT_BREAKER_TRIGGERED',
  CIRCUIT_BREAKER_RESET: 'CIRCUIT_BREAKER_RESET',
  INCIDENT_DETECTED: 'INCIDENT_DETECTED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  // From Execution
  ORDER_STAGED: 'ORDER_STAGED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
  ORDER_ESCALATED: 'ORDER_ESCALATED',
  BROKER_CIRCUIT_OPEN: 'BROKER_CIRCUIT_OPEN',
  // From Ledger
  BALANCE_UPDATED: 'BALANCE_UPDATED',
  PORTFOLIO_UPDATED: 'PORTFOLIO_UPDATED',
  LEDGER_ENTRY_RECORDED: 'LEDGER_ENTRY_RECORDED',
  RECONCILIATION_COMPLETED: 'RECONCILIATION_COMPLETED',
  LEDGER_PROCESSING_FAILED: 'LEDGER_PROCESSING_FAILED',
} as const;
