import { execSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { isEpic, epicRole, TERMINAL } from './rules.mjs';

const HEADER = `# Nestfolio Backlog

> Generated by \`backlog-lint --fix\` from \`docs/backlog/<id>.md\` frontmatter.
> Do not hand-edit. Discipline rules: see \`CLAUDE.md\` § "Backlog Discipline".

`;

const STATUS_ORDER = { active: 0, queued: 1, parking: 2, shipped: 3, dropped: 4 };
const statusRank = (f) => STATUS_ORDER[f.frontmatter?.status] ?? 9;

// Total scalar coercion: frontmatter values can be non-string (a list/number written
// by a skill one-liner). Coerce before any string op so render never crashes the --fix write.
const str = (x) => (typeof x === 'string' ? x : x == null ? '' : String(x));

function lineFor(f) {
  const type = f.frontmatter.type ? `[${str(f.frontmatter.type)}]` : '';
  const notesStr = str(f.frontmatter.notes).trim();
  const notes = notesStr ? ` — ${notesStr}` : '';
  const epicTag = f.frontmatter.epic ? ` \`[epic:${f.frontmatter.epic} · ${epicRole(f)}]\`` : '';
  return `[${f.id}](backlog/${f.id}.md) ${type}${notes}`.trim() + epicTag;
}

const todayISO = () => new Date().toISOString().slice(0, 10);

// Last-commit date for EVERY tracked file under docs/backlog, resolved in ONE
// `git log` pass (newest commit wins) instead of one subprocess per shipped file.
// The previous per-file approach spawned ~N git processes × 2 render passes (~25s
// on the live backlog — F-29). Keyed by absolute path to match `f.path`.
function gitLastCommitDateMap() {
  try {
    const root = execSync('git rev-parse --show-toplevel').toString().trim();
    const out = execSync(
      'git log --no-renames --date=short --format=%x00%ad --name-only -- docs/backlog',
      { cwd: root, maxBuffer: 64 * 1024 * 1024 },
    ).toString();
    const map = new Map();
    let cur = null;
    for (const line of out.split('\n')) {
      if (line.startsWith('\x00')) { cur = line.slice(1).trim() || null; continue; }
      const rel = line.trim();
      if (!rel) continue;
      const abs = join(root, rel);
      if (!map.has(abs)) map.set(abs, cur);   // log is newest-first → first hit is newest
    }
    return map;
  } catch { return new Map(); }
}

// Absolute paths of every file with pending (staged or unstaged) changes, computed
// once. A shipped file with uncommitted changes is being recorded *now*, so its last
// COMMITTED date is stale — see resolveShippedDate.
function gitDirtySet() {
  try {
    const root = execSync('git rev-parse --show-toplevel').toString().trim();
    const out = execSync('git status --porcelain', { cwd: root }).toString();
    const set = new Set();
    for (const line of out.split('\n')) {
      if (!line.trim()) continue;
      let rel = line.slice(3);                       // strip the "XY " status prefix
      const arrow = rel.indexOf(' -> ');             // rename: "old -> new" → keep new
      if (arrow !== -1) rel = rel.slice(arrow + 4);
      set.add(join(root, rel.replace(/^"|"$/g, '')));  // de-quote space-containing paths
    }
    return set;
  } catch { return new Set(); }
}

// All git-derived render inputs, gathered once (≤2 subprocesses total) and injectable
// so renderIndex can run fully hermetically in tests — pass an explicit gitInfo to avoid
// shelling out to git at all. Production callers use the default. (F-29 perf / F-31 hermeticity)
export function collectGitInfo() {
  return { dirty: gitDirtySet(), dateMap: gitLastCommitDateMap() };
}

// Pure: resolve a shipped item's "Recently Shipped" date. Precedence:
//   1. explicit `closed:` frontmatter always wins — the AUTHORITATIVE date, now stamped
//      at ship time by both ship steps (/backlog-next 6.5, /backlog-next-epic E7.4), so the
//      recorded date never depends on commit timing. This fixes the across-midnight drift
//      where a dirty→today write disagreed with a later git-commit-date regen (F-30);
//   2. else a DIRTY file (an uncommitted ship recorded without `closed:`) → `today`, a
//      fallback that keeps `--fix` stable before vs after the ship commit;
//   3. else the last committed date (batched lookup);
//   4. else a sentinel that sorts to the bottom.
// Stamping `closed:` per-item at ship time (precedence 1) is the durable fix; (2) remains a
// safety net for items shipped without it and for pre-F-30 history (no backfill needed).
export function resolveShippedDate({ closed, dirty, gitDate, today }) {
  if (closed) return closed;
  if (dirty) return today;
  return gitDate ?? '0000-00-00';
}

// One rollup block per live epic: done_when + core/captured progress + member list.
function renderEpicBlock(epic, files) {
  const members = files.filter(f => f.frontmatter?.epic === epic.id);
  const core = members.filter(m => epicRole(m) === 'core');
  const captured = members.filter(m => epicRole(m) === 'captured');
  const done = (arr) => arr.filter(m => TERMINAL.has(m.frontmatter?.status)).length;

  const status = epic.frontmatter?.status;
  const notesStr = str(epic.frontmatter?.notes).trim();
  const notes = notesStr ? ` — ${notesStr}` : '';
  const lines = [`### [${epic.id}](backlog/${epic.id}.md) \`[epic · ${status}]\`${notes}`];
  const dwStr = str(epic.frontmatter?.done_when).trim();
  if (dwStr) lines.push(`done_when: ${dwStr}`);
  lines.push(`rollup: core ${done(core)}/${core.length} done · captured ${done(captured)}/${captured.length} done`);

  const ordered = [...members].sort((a, b) =>
    statusRank(a) - statusRank(b) || a.id.localeCompare(b.id));
  const byRole = [
    ...ordered.filter(m => epicRole(m) === 'core'),
    ...ordered.filter(m => epicRole(m) === 'captured'),
  ];
  if (byRole.length === 0) lines.push('_(no members)_');
  for (const m of byRole) {
    lines.push(`- ${epicRole(m)} · ${m.frontmatter?.status} · [${m.id}](backlog/${m.id}.md)`);
  }
  return lines.join('\n');
}

export function renderIndex(files, gitInfo = collectGitInfo()) {
  const epics = files.filter(isEpic);
  const nonEpic = files.filter(f => !isEpic(f));

  const liveEpics = epics
    .filter(e => ['active', 'queued', 'parking'].includes(e.frontmatter?.status))
    .sort((a, b) =>
      statusRank(a) - statusRank(b)
      || (a.frontmatter?.rank ?? 0) - (b.frontmatter?.rank ?? 0)
      || a.id.localeCompare(b.id));

  // Members of an ACTIVE delivery epic are shown ONLY in that epic's rollup, never
  // flat — they are orchestrated by /backlog-next-epic and must not be surfaced as
  // standalone picks by /backlog-next. (Theme-/queued-epic members keep their flat
  // listing with the [epic:X·role] tag, per the 2026-06-16 rendering model.)
  const activeEpicIds = new Set(
    epics.filter(e => e.frontmatter?.status === 'active').map(e => e.id),
  );
  const isActiveEpicMember = (f) =>
    f.frontmatter?.epic != null && activeEpicIds.has(f.frontmatter.epic);

  const active = nonEpic.filter(f => f.frontmatter?.status === 'active' && !isActiveEpicMember(f));
  const queued = nonEpic.filter(f => f.frontmatter?.status === 'queued' && !isActiveEpicMember(f))
    .sort((a, b) => (a.frontmatter.rank ?? 0) - (b.frontmatter.rank ?? 0));
  const parking = nonEpic.filter(f => f.frontmatter?.status === 'parking' && !isActiveEpicMember(f));
  const shippedAll = files.filter(f => f.frontmatter?.status === 'shipped'); // incl. shipped epics
  const { dirty, dateMap } = gitInfo;
  const today = todayISO();
  const shippedRecent = shippedAll
    .map(f => {
      const isDirty = dirty.has(f.path);
      return {
        f,
        date: resolveShippedDate({
          closed: f.frontmatter.closed,
          dirty: isDirty,
          gitDate: isDirty ? null : (dateMap.get(f.path) ?? null), // batched lookup; dirty skips it
          today,
        }),
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date))
    .slice(0, 10);

  // Parking health: the bounded tracking surface. Theme epics are durable
  // root-cause buckets; orphans are un-clustered standalone parking items to drive → 0.
  const themeEpics = epics.filter(e => e.frontmatter?.status === 'parking').length;
  const orphans = parking.filter(f => f.frontmatter?.epic == null).length;

  const lines = [HEADER];
  lines.push('## EPICS\n');
  lines.push(liveEpics.length ? liveEpics.map(e => renderEpicBlock(e, files)).join('\n\n') : '_(none)_');
  lines.push(`\n**Parking health:** ${themeEpics} theme epic(s), ${orphans} orphan(s) — drive orphans → 0 with \`/backlog-themes\``);
  lines.push('\n## ACTIVE\n');
  if (active.length === 0) lines.push('_(none)_\n');
  for (const f of active) lines.push(`- ${lineFor(f)}`);
  lines.push('\n## QUEUED\n');
  if (queued.length === 0) lines.push('_(none)_\n');
  queued.forEach((f, i) => lines.push(`${i + 1}. ${lineFor(f)}`));
  lines.push('\n## LATER\n');
  if (parking.length === 0) lines.push('_(none)_\n');
  for (const f of parking) lines.push(`- ${lineFor(f)}`);
  lines.push('\n## Recently Shipped (last 10)\n');
  if (shippedRecent.length === 0) lines.push('_(none)_\n');
  for (const { f, date } of shippedRecent) lines.push(`- ${date} — ${lineFor(f)}`);
  return lines.join('\n') + '\n';
}

export function ruleIndexMatches(files, indexPath) {
  if (!existsSync(indexPath)) {
    return [{ rule: 'index-matches', file: null, message: `${indexPath} not found` }];
  }
  const expected = renderIndex(files);
  const actual = readFileSync(indexPath, 'utf8');
  if (actual !== expected) {
    return [{ rule: 'index-matches', file: null,
      message: `BACKLOG.md is out of date — run backlog-lint --fix` }];
  }
  return [];
}
