import { execSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';

const HEADER = `# Nestfolio Backlog

> Generated by \`backlog-lint --fix\` from \`docs/backlog/<id>.md\` frontmatter.
> Do not hand-edit. Discipline rules: see \`CLAUDE.md\` § "Backlog Discipline".

`;

function lineFor(f) {
  const type = f.frontmatter.type ? `[${f.frontmatter.type}]` : '';
  const notes = f.frontmatter.notes?.trim() ? ` — ${f.frontmatter.notes.trim()}` : '';
  return `[${f.id}](backlog/${f.id}.md) ${type}${notes}`.trim();
}

function gitClosedDate(path) {
  try {
    return execSync(`git log -1 --format=%ad --date=short -- "${path}"`).toString().trim() || null;
  } catch { return null; }
}

export function renderIndex(files) {
  const active = files.filter(f => f.frontmatter?.status === 'active');
  const queued = files.filter(f => f.frontmatter?.status === 'queued')
    .sort((a, b) => (a.frontmatter.rank ?? 0) - (b.frontmatter.rank ?? 0));
  const parking = files.filter(f => f.frontmatter?.status === 'parking');
  const shippedAll = files.filter(f => f.frontmatter?.status === 'shipped');
  const shippedRecent = shippedAll
    .map(f => ({ f, date: f.frontmatter.closed ?? gitClosedDate(f.path) ?? '0000-00-00' }))
    .sort((a, b) => b.date.localeCompare(a.date))
    .slice(0, 10);

  const lines = [HEADER];
  lines.push('## ACTIVE\n');
  if (active.length === 0) lines.push('_(none)_\n');
  for (const f of active) lines.push(`- ${lineFor(f)}`);
  lines.push('\n## QUEUED\n');
  if (queued.length === 0) lines.push('_(none)_\n');
  queued.forEach((f, i) => lines.push(`${i + 1}. ${lineFor(f)}`));
  lines.push('\n## LATER\n');
  if (parking.length === 0) lines.push('_(none)_\n');
  for (const f of parking) lines.push(`- ${lineFor(f)}`);
  lines.push('\n## Recently Shipped (last 10)\n');
  if (shippedRecent.length === 0) lines.push('_(none)_\n');
  for (const { f, date } of shippedRecent) lines.push(`- ${date} — ${lineFor(f)}`);
  return lines.join('\n') + '\n';
}

export function ruleIndexMatches(files, indexPath) {
  if (!existsSync(indexPath)) {
    return [{ rule: 'index-matches', file: null, message: `${indexPath} not found` }];
  }
  const expected = renderIndex(files);
  const actual = readFileSync(indexPath, 'utf8');
  if (actual !== expected) {
    return [{ rule: 'index-matches', file: null,
      message: `BACKLOG.md is out of date — run backlog-lint --fix` }];
  }
  return [];
}
