/**
 * Cross-domain event types published by the execution domain.
 * These are the events that other domains may consume.
 */
export const ExecutionCrossDomainEventTypes = {
  // → Investor
  ORDER_STAGED: 'ORDER_STAGED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  ORDER_ESCALATED: 'ORDER_ESCALATED',
  BROKER_CIRCUIT_OPEN: 'BROKER_CIRCUIT_OPEN',
  // → Ledger
  ORDER_FILLED: 'ORDER_FILLED',
  ORDER_PARTIALLY_FILLED: 'ORDER_PARTIALLY_FILLED',
  DEPOSIT_DETECTED: 'DEPOSIT_DETECTED',
  WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
  CORPORATE_ACTION_APPLIED: 'CORPORATE_ACTION_APPLIED',
  PORTFOLIO_SNAPSHOT_IMPORTED: 'PORTFOLIO_SNAPSHOT_IMPORTED',
  ALPACA_ACCOUNT_SNAPSHOT: 'ALPACA_ACCOUNT_SNAPSHOT',
  // → Advisory
  PORTFOLIO_DRIFT_DETECTED: 'PORTFOLIO_DRIFT_DETECTED',
  BROKER_SESSION_LOST: 'BROKER_SESSION_LOST',
  STREAM_DISCONNECTED: 'STREAM_DISCONNECTED',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
} as const;

/**
 * Events ingested by the execution domain from external domain buses.
 * The execution adapter deploys EB rules on these foreign buses to pull events into ExecutionBus.
 */
export const ExecutionIngestEventTypes = {
  // From Advisory
  DECISION_APPROVED: 'DECISION_APPROVED',
  DECISION_PACKET_CREATED: 'DECISION_PACKET_CREATED',
  USER_CONFIRMED: 'USER_CONFIRMED',
  CIRCUIT_BREAKER_TRIGGERED: 'CIRCUIT_BREAKER_TRIGGERED',
  CIRCUIT_BREAKER_RESET: 'CIRCUIT_BREAKER_RESET',
  // From Investor
  DEPOSIT_INITIATED: 'DEPOSIT_INITIATED',
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  ACCOUNT_CLOSURE_REQUESTED: 'ACCOUNT_CLOSURE_REQUESTED',
  EXECUTION_MODE_CHANGED: 'EXECUTION_MODE_CHANGED',
} as const;
