import { Injectable } from '@angular/core';
import { getRuntimeConfig, RuntimeConfig } from './app.config';

/**
 * Injectable service that provides access to the runtime configuration.
 * The config is loaded at bootstrap via APP_INITIALIZER (loadRuntimeConfig),
 * so it is guaranteed to be available by the time any component or service injects this.
 *
 * In production, values come from /assets/config.json (generated by CI/CD).
 * In development, values come from environment.ts.
 */
@Injectable({ providedIn: 'root' })
export class RuntimeConfigService {
  get config(): RuntimeConfig {
    return getRuntimeConfig();
  }

  get auth(): RuntimeConfig['auth'] {
    return this.config.auth;
  }

  get appsync(): RuntimeConfig['appsync'] {
    return this.config.appsync;
  }
}
