export const InvestorEventTypes = {
  // investor-web
  USER_REGISTERED: 'USER_REGISTERED',
  USER_AUTHENTICATED: 'USER_AUTHENTICATED',
  USER_SESSION_EXPIRED: 'USER_SESSION_EXPIRED',
  USER_DELETION_REQUESTED: 'USER_DELETION_REQUESTED',
  PII_REMOVED: 'PII_REMOVED',
  TENANT_ANONYMIZED: 'TENANT_ANONYMIZED',

  // investor-bff
  ONBOARDING_ANSWER_RECORDED: 'ONBOARDING_ANSWER_RECORDED',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  GOAL_SET: 'GOAL_SET',
  GOAL_UPDATED: 'GOAL_UPDATED',
  RISK_PROFILE_SET: 'RISK_PROFILE_SET',
  RISK_PROFILE_UPDATED: 'RISK_PROFILE_UPDATED',
  MANDATE_GRANTED: 'MANDATE_GRANTED',
  MANDATE_UPDATED: 'MANDATE_UPDATED',
  MANDATE_REVOKED: 'MANDATE_REVOKED',
  OPERATING_MODE_SELECTED: 'OPERATING_MODE_SELECTED',
  OPERATING_MODE_CHANGED: 'OPERATING_MODE_CHANGED',
  DEPOSIT_INITIATED: 'DEPOSIT_INITIATED',
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  ACCOUNT_CLOSURE_REQUESTED: 'ACCOUNT_CLOSURE_REQUESTED',
  ACCOUNT_CLOSED: 'ACCOUNT_CLOSED',
  BROKER_AUTHORIZATION_REVOKED: 'BROKER_AUTHORIZATION_REVOKED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',

  // investor-ctrl
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_DELIVERED: 'NOTIFICATION_DELIVERED',
  MONTHLY_REPORT_GENERATED: 'MONTHLY_REPORT_GENERATED',
} as const;

export type InvestorEventType =
  (typeof InvestorEventTypes)[keyof typeof InvestorEventTypes];
