import { eventName } from '@nestfolio/event-types';

export const AdvisoryBffEventTypes = {
  ADVISORY_STATUS_UPDATED: eventName('ADVISORY_STATUS_UPDATED'),
  USER_CONFIRMED: eventName('USER_CONFIRMED'),
  USER_REJECTED: eventName('USER_REJECTED'),
  USER_VIEWED_EXPLANATION: eventName('USER_VIEWED_EXPLANATION'),
  DECISION_READ_MODEL_CREATED: eventName('DECISION_READ_MODEL_CREATED'),
  DECISION_READ_MODEL_UPDATED: eventName('DECISION_READ_MODEL_UPDATED'),
  USER_INTERACTION_CREATED: eventName('USER_INTERACTION_CREATED'),
  USER_INTERACTION_UPDATED: eventName('USER_INTERACTION_UPDATED'),
} as const;
