import { eventName } from '@nestfolio/event-types';

export const InvestorCtrlEventTypes = {
  NOTIFICATION_CREATED: eventName('NOTIFICATION_CREATED'),
  NOTIFICATION_SENT: eventName('NOTIFICATION_SENT'),
  NOTIFICATION_DELIVERED: eventName('NOTIFICATION_DELIVERED'),
  MONTHLY_REPORT_GENERATED: eventName('MONTHLY_REPORT_GENERATED'),
  MONTHLY_REPORT_CREATED: eventName('MONTHLY_REPORT_CREATED'),
  MONTHLY_REPORT_UPDATED: eventName('MONTHLY_REPORT_UPDATED'),
} as const;
