export const InvestorCtrlEventTypes = {
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_DELIVERED: 'NOTIFICATION_DELIVERED',
  MONTHLY_REPORT_GENERATED: 'MONTHLY_REPORT_GENERATED',
} as const;
